# Generated by Django 4.1.2 on 2023-08-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_name_topic_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='names',
            new_name='name',
        ),
    ]
